config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root 'pages#index'
  resources :projects
  resources :project_types
  resources :positions
  resources :members
  get 'dashboard/statistics', to: 'dashboard#statistics'
  get 'dashboard/projects', to: 'dashboard#projects'
  get 'dashboard/managers', to: 'dashboard#managers'
  get 'dashboard/developers', to: 'dashboard#developers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_project_types, only: :projects

  def statistics
    @projects_count = @current_enterprise.projects.count

    @starting_projects_count = @current_enterprise.projects.where(state: :Starting).count
    @middle_projects_count = @current_enterprise.projects.where(state: :Middle).count
    @finishing_projects_count = @current_enterprise.projects.where(state: :Finishing).count
    @support_projects_count = @current_enterprise.projects.where(state: :Support).count

    @project_types = @current_enterprise.project_types
  end

  def projects
    @q = @current_enterprise.projects.ransack(params[:q])
    @projects = @q.result.order(state: :desc)
  end

  def managers
    managers_ids = ManagerProject.joins(:member).where(members: {enterprise_id: @current_enterprise.id}).pluck(:member_id).uniq
    @managers = Member.where(id: managers_ids).order(load: :desc)
  end

  def developers
    developers_ids = MemberProject.joins(:member).where(members: {enterprise_id: @current_enterprise.id}).pluck(:member_id).uniq
    @developers = Member.where(id: developers_ids).order(load: :desc)
  end

  private
 
  def set_project_types
    @project_types = @current_enterprise.project_types
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_navbar.html.erb
    <% statistics ||= "" %>
    <% projects ||= "" %>
    <% managers ||= "" %>
    <% developers ||= "" %>

    <h1 class="title">Dashboard</h1>

    <div class="tabs is-large is-centered dashboard">
      <ul>
        <li class="<%= statistics %>"><%=link_to t(:statistics), dashboard_statistics_path %></li>
        <li class="<%= projects %>"><%=link_to t(:projects), dashboard_projects_path %></li>
        <li class="<%= managers %>"><%=link_to t(:managers), dashboard_managers_path %></li>
        <li class="<%= developers %>"><%=link_to t(:consultants), dashboard_developers_path %></li>
      </ul>
    </div>

app/views/dashboard/developers.html.erb
<section class="section dashboard">
  <div class="container">

    <%= render partial: "navbar", locals: { developers: "is-active" }%>

    <div class='columns is-multiline mt-5'>
      <% @developers.each do |developer| %>
        <div class='column is-one-quarter'>
          <div class="card">
            <header class="card-header" style="background-color: #0676ED">
              <p class="card-header-title has-text-white">
                  <%= developer.name %> - <%=Member.human_attribute_name('load')%>: <%= developer.load %>
              </p>
            </header>
              <div class="card-content">
                <div class="content">
                  <p><strong><%=Project.model_name.human(count: 2)%>: </strong></p>
                  <% developer.developed_projects.each do |project| %>
                    <%= project.name %> - <i><strong><%= t("enums.project.state.#{project.state}") %></strong></i><br>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<section class="section">
  <div class="container">
    <%#= image_tag '/dashboard.png'%>

    <%= render partial: "navbar", locals: { statistics: "is-active" }%>

    <div class="tile is-ancestor">
      <div class="tile is-parent">
        <div class="tile is-child box ">
          <p class="title is-1 is-spaced "><%= @projects_count%></p> 
          <p class="subtitle">Projects</p> 
        </div>
      </div>

      <div class="tile is-4 is-vertical is-parent">
        <% @project_types.each do |pt| %>
          <div class="tile is-child box">
            <p class="title is-5"><%= pt.name %></p>
            <p class="subtitle"><%= pt.projects.count %></p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <div class="card">
          <div class="card-content">
            <p class="title is-5 ">Starting Projects</p>
            <p class="subtitle "><%= @starting_projects_count%></p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <div class="card-content">
            <p class="title is-5 ">Middle Projects</p>
            <p class="subtitle "><%= @middle_projects_count%></p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <div class="card-content">
            <p class="title is-5 ">Finishing Projects</p>
            <p class="subtitle "><%= @finishing_projects_count%></p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <div class="card-content">
            <p class="title is-5 ">Support Projects</p>
            <p class="subtitle "><%= @support_projects_count%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/managers.html.erb
<section class="section dashboard">
  <div class="container">

    <%= render partial: "navbar", locals: { managers: "is-active" }%>

    <div class='columns is-multiline mt-5'>
      <% @managers.each do |manager| %>
        <div class='column is-one-quarter'>
          <div class="card">
            <header class="card-header" style="background-color: #0676ED">
              <p class="card-header-title has-text-white">
                  <%= manager.name %> - <%=Member.human_attribute_name('load')%>: <%= manager.load %>
              </p>
            </header>
              <div class="card-content">
                <div class="content">
                  <p><strong><%=t(:managed_projects)%>: </strong></p>
                  <% manager.managed_projects.each do |project| %>
                      <%= project.name %> - <i><strong><%= t("enums.project.state.#{project.state}") %></strong></i><br>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/projects.html.erb
<section class="section dashboard">
  <div class="container">
    <%= render partial: "navbar", locals: { projects: "is-active" }%>
    
    <%= search_form_for @q, url: dashboard_projects_path do |f|%>
      <div class="field is-grouped">
        <div class="field mr-2">
          <%= f.label :state, class:"label" %>  
          <div class="control">
            <div class="select ">
              <%= f.select :state_eq, state_enum_select_options(Project.states.keys), include_blank: 'Todos' %>
            </div>
          </div>
        </div>
        <div class="field mr-2">
          <%= f.label :complexity, class:"label" %>  
          <div class="control">
            <div class="select ">
              <%= f.select :complexity_eq, complexity_enum_select_options(Project.complexities.keys), include_blank: 'Todos' %>
            </div>
          </div>
        </div>
        <div class="field mr-2">
          <%= f.label ProjectType.model_name.human, class:"label" %>  
          <div class="control">
            <div class="select ">
              <%= f.collection_select :project_type_id_eq, @project_types, :id, :name, include_blank: 'Todos' %>
            </div>
          </div>
        </div>
        <div class="control mt-5 pt-2 mr-2">
          <%= f.submit class:"button "%>
        </div>
      </div>
    <% end %>

    <div class='columns is-multiline mt-5'>
      <% @projects.each do |project| %>
        <div class='column is-one-quarter'>
          <div class="card">
            <header class="card-header" style="background-color: #0676ED">
              <p class="card-header-title has-text-white">
              <%= project.name %>
              </p>
            </header>
              <div class="card-content">
                <div class="content">
                <strong><%= t(:managers)%>:</strong>
                <% project.managers.each do |manager| %>
                  <%= manager.try(:name) %>
                <% end %>
                <br>
                <strong><%= t(:consultants)%>:</strong>
                <% project.developers.each do |developer| %>
                  <%= developer.name %>
                <% end %>
                <hr>
                <strong><%= Project.human_attribute_name('state')%>: </strong> <%= t("enums.project.state.#{project.state}") %>
                <br>
                <strong><%= Project.human_attribute_name('complexity')%>: </strong> <%= t("enums.project.complexity.#{project.complexity}") %>
                <br>
                <strong><%= Project.human_attribute_name('internal')%>: </strong> <%= t("boolean.#{project.internal}") %>
                </div>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/statistics.html.erb
<section class="section dashboard">
  <div class="container">
    <%#= image_tag '/dashboard.png'%>

    <%= render partial: "navbar", locals: { statistics: "is-active" }%>

    <div class="tile is-ancestor">
      <div class="tile is-parent">
        <div class="tile is-child box" style="background-color: #0676ED">
          <p class="title is-1 is-spaced has-text-white"><%= @projects_count%></p> 
          <p class="subtitle has-text-white">Projects</p> 
        </div>
      </div>

      <div class="tile is-4 is-vertical is-parent">
        <% @project_types.each do |pt| %>
          <div class="tile is-child box">
            <p class="title is-5"><%= pt.name %></p>
            <p class="subtitle"><%= pt.projects.count %></p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <div class="card">
          <div class="card-content">
            <p class="title is-5 ">Starting Projects</p>
            <p class="subtitle "><%= @starting_projects_count%></p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <div class="card-content">
            <p class="title is-5 ">Middle Projects</p>
            <p class="subtitle "><%= @middle_projects_count%></p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <div class="card-content">
            <p class="title is-5 ">Finishing Projects</p>
            <p class="subtitle "><%= @finishing_projects_count%></p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <div class="card-content">
            <p class="title is-5 ">Support Projects</p>
            <p class="subtitle "><%= @support_projects_count%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>