config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root 'pages#index'
  resources :projects
  resources :project_types
  resources :positions
  resources :members
  get 'dashboard/statistics', to: 'dashboard#statistics'
  get 'dashboard/projects', to: 'dashboard#projects'
  get 'dashboard/managers', to: 'dashboard#managers'
  get 'dashboard/developers', to: 'dashboard#developers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
  after_save :update_members_loads

  belongs_to :enterprise

  has_many :member_positions, dependent: :destroy
  has_many :members, through: :member_positions

  enum load: { no_load: 0, low: 10, medium_low: 15, medium: 20, medium_high: 25, high:30 }

  def update_members_loads
    members.each(&:calc_member_load)
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @q = @current_enterprise.positions.ransack(params[:q])
    @positions = @q.result.order(load: :desc)
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = @current_enterprise.positions.build(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_position
    @position = @current_enterprise.positions.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def position_params
    params.require(:position).permit(:name, :load)
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
  def load_enum_select_options(keys)
    keys.map { |key| [t("enums.position.load.#{key}"), key] }
  end
end

app/views/positions/_form.html.erb
<% if position.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

    <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="card mt-3">
  <div class="card-content">
    <%= form_with(model: position, local: true) do |f| %>
      
      <div class="field">
        <%= f.label t(:name) , class:"label"%>
        <div class="control">
          <%= f.text_field :name , class:"input", type:"text"%>
        </div>
      </div>

      <div class="field mr-2">
        <%= f.label t(:load), class:"label" %>
        <p class="control is-expanded ">
          <div class="select">
            <%= f.select :load, load_enum_select_options(Position.loads.keys), class:"select" %>
          </div>
        </p>
      </div>

      <div class="buttons">
        <button class="button is-primary"><%=t('actions.submit')%></button>
      </div>
    <% end %>
  </div>
</div>

app/views/positions/edit.html.erb
<div class="columns is-centered is-mobile mt-5">
  <div class="column is-three-quarters-mobile is-two-thirds-tablet is-half-desktop is-one-fifths-widescreen">
    <h1 class="subtitle"><%=t('actions.position.edit')%></h1>

    <%= render 'form', position: @position %>
    <div class="mt-4 ml-2">
      <%= link_to t('actions.show'), @position %> |
      <%= link_to t('actions.back'), positions_path %>
    </div>
  </div>
</div>

app/views/positions/index.html.erb
<section class="section">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <%#= image_tag "/positions.png"%>

    <h1 class="title"><%=Position.model_name.human(count: 2)%></h1>

    <div class="table-container">
      <table class="table is-bordered is-striped is-hoverable is-fullwidth">
        <thead>
          <tr>
            <th class="left-corner"><%= sort_link(@q, :name)%></th>
            <th><%= sort_link(@q, :load)%></th>
            <th class="right-corner has-text-center"><%=t(:options)%></th>
          </tr>
        </thead>

        <tbody>
          <% @positions.each do |position| %>
            <tr>
              <td class="left-corner"><%= position.name %></td>
              <td><%= t("enums.position.load.#{position.load}") %></td>
              <td class="right-corner has-text-centered">
                <div class="crud-hover">  
                  <div class="card crud-options">
                    <footer class="card-footer">
                      <%= link_to "/positions/#{position.id}/edit", class:"crud-edit" do%>
                        <i class="fas fa-edit"></i> 
                        <div class="crud-text"> 
                          Editar
                        </div>
                      <% end %>
                      <%= link_to "/positions/#{position.id}" , method: :delete, data: { confirm: 'Are you sure?' }, class:"crud-delete" do%>
                        <i class="fas fa-trash-alt"></i> 
                        <div class="crud-text">  
                          Remover
                        </div>
                      <% end %>
                      <div class="crud-options-triangle">
                      </div>  
                    </footer>
                  </div>
                </div>

                <i class="fas fa-ellipsis-h"></i>
              </td>

              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>

    <button class="button is-success ">
      <%= link_to new_position_path do %>
        <i class="fas fa-plus"></i> Novo Cargo
      <% end %>
    </button>
  </div>
</section>

app/views/positions/new.html.erb
<div class="columns is-centered mt-5">
  <div class="column is-one-third">
    <h1 class="subtitle">New Position</h1>

    <%= render 'form', position: @position %>
    <div class="mt-4 ml-2">
      <%= link_to t('actions.back'), positions_path %>
    </div>
  </div>
</div>

app/views/positions/show.html.erb
<div class="columns is-centered is-mobile mt-5">
  <div class="column is-four-fifths-mobile is-half-tablet is-two-fifths-desktop is-one-third-widescreen">
    <p id="notice"><%= notice %></p>
    <div class="card mt-3">
      <div class="card-content">

        <h2 class="subtitle">
          <strong><%=t(:name)%>:</strong> <%= @position.name %> 
        </h2>
        <hr>

        <h2 class="subtitle">
          <strong><%=t(:load)%>:</strong> <%= t("enums.position.load.#{@position.load}") %> 
        </h2>
        <hr>

        <%= link_to t('actions.edit'), edit_position_path(@position) %> |
        <%= link_to t('actions.back'), positions_path %>
      </div>
    </div>
  </div>
</div>
    