config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root 'pages#index'
  resources :projects
  resources :project_types
  resources :positions
  resources :members
  get 'dashboard/statistics', to: 'dashboard#statistics'
  get 'dashboard/projects', to: 'dashboard#projects'
  get 'dashboard/managers', to: 'dashboard#managers'
  get 'dashboard/developers', to: 'dashboard#developers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script>
    $(function(){
        $('a').each(function(){
            if ($(this).prop('href') == window.location.href) {
                $(this).addClass('active'); $(this).parents('li').addClass('active');
            }
        });
    });
</script>


<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <%= image_tag '/logo.png' %>
    <% end %>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar" data-turbolinks="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbar" class="navbar-menu">
      <%= link_to dashboard_statistics_path, class:"navbar-item" do %>
        <i class="fas fa-project-diagram"></i> Dashboard
      <% end %>
      <%= link_to projects_path, class: "navbar-item" do %>
        <i class="fas fa-window-restore"></i> Projetos
      <% end %>
      <%= link_to members_path, class: "navbar-item" do %>
        <i class="fas fa-user-friends"></i> Membros
      <% end %>
      
      <%= link_to project_types_path, class: "navbar-item tipodeprojeto-item" do %>
        <i class="fas fa-laptop-code"></i> Tipos de Projeto
      <% end %>
      <%= link_to positions_path, class: "navbar-item" do %>
        <i class="fas fa-user-tag"></i> Cargo
      <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
            <span class="mx-5">Logado como : <%= @current_enterprise_name %> </span>
            <strong><%= link_to 'Log out', destroy_admin_session_path, method: :delete, class: "button is-primary" %></strong>
        </div>
      </div>
    </div>
  </div>

</nav>

<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>AlocacaoGti</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">

  </head>

  <body>
    <% if user_signed_in? %>
      <%= render partial: 'layouts/navbar'%>
    <% end %>
    <%= yield %>
  </body>
</html>