config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root 'pages#index'
  resources :projects
  resources :project_types
  resources :positions
  resources :members
  get 'dashboard/statistics', to: 'dashboard#statistics'
  get 'dashboard/projects', to: 'dashboard#projects'
  get 'dashboard/managers', to: 'dashboard#managers'
  get 'dashboard/developers', to: 'dashboard#developers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord

  after_save :calc_member_load

  belongs_to :enterprise

  has_many :member_positions, dependent: :destroy
  has_many :positions, through: :member_positions

  has_many :member_projects, dependent: :destroy
  has_many :developed_projects, through: :member_projects, source: :project #1 ATRIBUTO: Nome da Relação ; 2 ATRIBUTO: Através de que tabela a relação ocorre

  has_many :manager_projects, dependent: :destroy
  has_many :managed_projects, through: :manager_projects, source: :project

  accepts_nested_attributes_for :member_positions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :member_projects, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :manager_projects, reject_if: :all_blank, allow_destroy: true

  def calc_member_load
    update_columns(load: calc_development_load + calc_managing_load + calc_position_load)
    #Update columns ignora toda a camada que envolve o active record, ou seja, 
    #ele não gerará um loop infinito por conta do after_save
    #Futuramente procurar uma forma de fugir dos callbacks, procurar por "operation"
  end

  #Cálculo da Carga do Cargo
  def calc_position_load
    positions.sum(:load) #Soma da Carga de todos os cargos associados a essa pessoa
  end

  def calc_development_load
    projects_load = 0
    developed_projects.each do |project| #Relação entre 
      projects_load += calc_project_development_load(project)
    end
    projects_load
  end

  def calc_managing_load
    projects_load = 0
    managed_projects.each do |project|
      projects_load += calc_project_managing_load(project)
    end
    projects_load
  end

  def calc_project_development_load(project)
    project.project_type.load_before_type_cast * complexity_factor(project) * state_factor(project)
  end
  
  def calc_project_managing_load(project)
    project.project_type.load_before_type_cast * complexity_factor(project) * manager_state_factor(project)
  end

  def complexity_factor(project)
    case project.complexity
    when 'Beginner' then 1.0
    when 'Intermediate' then 1.5
    when 'Experient' then 2.0
    else 1
    end
  end

  def state_factor(project)
    case project.state
    when 'Stoped' then 0.1
    when 'Starting' then 1
    when 'Middle' then 1
    when 'Finishing' then 1
    when 'Support' then 0.3
    else 1
    end
  end

  def manager_state_factor(project)
    case project.state
    when 'Stoped' then 0.1
    when 'Starting' then 1.0
    when 'Middle' then 0.5
    when 'Finishing' then 1.0
    when 'Support' then 0.1
    else 1
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :set_projects, only: [:edit, :new]
  before_action :set_positions, only: [:edit, :new]

  # GET /members
  # GET /members.json
  def index
    @q = @current_enterprise.members.ransack(params[:q])
    @members = @q.result.order(load: :desc)
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @development_load = @member.calc_development_load
    @management_load = @member.calc_managing_load
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = @current_enterprise.members.build(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = @current_enterprise.members.find(params[:id])
  end

  def set_projects
    @projects = @current_enterprise.projects
  end

  def set_positions
    @positions = @current_enterprise.positions
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(
      :name, :load, :exit_cycle,
      member_positions_attributes: %i[id position_id _destroy],
      member_projects_attributes: %i[id project_id _destroy],
      manager_projects_attributes: %i[id project_id _destroy]
    )
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<% if member.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

    <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="card mt-3">
  <div class="card-content">

    <%= form_for @member do |f| %>
      <div class="field">
        <%= f.label :name , class:"label"%>
        <div class="control">
          <%= f.text_field :name , class:"input", type:"text"%>
        </div>
      </div>
      
      <div class="field">
        <div class="control">
          <%= f.label :exit_cycle %>
          <label class="checkbox">
            <%= f.check_box :exit_cycle, type:"checkbox" %>
          </label>
        </div>
      </div>

      <hr>
      <h3><%=t(:managed_projects)%>: </h3>

      <div id='managing_projects'>
        <%= f.fields_for :manager_projects do |manager_project| %>
          <%= render 'manager_project_fields', :f =>  manager_project %>
        <% end %>
        <div class='links my-4'>
          <%= link_to_add_association t('actions.project.add_project'), f , :manager_projects %>
        </div>
      </div>

      <hr>
      <h3><%=t(:developed_projects)%>: </h3>

      <div id='member_projects'>
        <%= f.fields_for :member_projects do |member_project| %>
          <%= render 'member_project_fields', :f => member_project %>
        <% end %>
        <div class='links my-4'>
          <%= link_to_add_association t('actions.project.add_project'), f , :member_projects %>
        </div>
      </div>

      <hr>
      <h3><%=Position.model_name.human(count:2)%>: </h3>

      <div id='member_positions'>
        <%= f.fields_for :member_positions do |member_position| %>
          <%= render 'member_position_fields', :f => member_position %>
        <% end %>
        <div class='links my-4'>
          <%= link_to_add_association t('actions.position.add_position'), f, :member_positions %>
        </div>
      </div>

      <div class="buttons">
        <button class="button is-primary"><%=t('actions.submit')%></button>
      </div>
    <% end %>
  </div>
</div>

app/views/members/_manager_project_fields.html.erb
<div class='nested-fields'>
  <div class="select mt-2">
   <%= f.collection_select(:project_id, @projects, :id, :name) %>
  </div>
  <%= link_to_remove_association t('actions.project.remove_project'), f , class:"m-4" %>
</div>

app/views/members/_member_position_fields.html.erb
<div class='nested-fields'>
  <div class="select mt-2">
   <%= f.collection_select(:position_id, @positions, :id, :name) %>
  </div>
  <%= link_to_remove_association t('actions.position.remove_position'), f , class:"m-4" %>
</div>

app/views/members/_member_project_fields.html.erb
<div class='nested-fields'>
  <div class="select mt-2">
   <%= f.collection_select(:project_id, @projects, :id, :name) %>
  </div>
  <%= link_to_remove_association t('actions.project.remove_project'), f , class:"m-4" %>
</div>

app/views/members/edit.html.erb
<div class="columns is-centered is-mobile mt-5">
  <div class="column is-three-quarters-mobile is-two-thirds-tablet is-half-desktop is-one-fifths-widescreen">
    <h1 class="subtitle"><%=t('actions.member.edit')%></h1>

    <%= render 'form', member: @member %>
    <div class="mt-4 ml-2">
      <%= link_to t('actions.show'), @member %> |
      <%= link_to t('actions.back'), members_path %>
    </div>
  </div>
</div>

app/views/members/index.html.erb
<section class="section">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <%#= image_tag "/members.png"%>
    <h1 class="title"><%=Member.model_name.human(count:2)%></h1>
    <div class="table-container">
      <table class="table is-bordered is-striped is-hoverable is-fullwidth">
        <thead>
          <tr>
            <th class="left-corner"><%= sort_link(@q, :name) %></th>
            <th><%= sort_link(@q, :load) %></th>
            <th><%= sort_link(@q, :exit_cycle) %></th>
            <th colspan="3" class="has-text-centered right-corner"><%=t(:options)%></th>
          </tr>
        </thead>

        <tbody>
          <% @members.each do |member| %>
            <tr>
              <td onclick="location.href='<%="/members/#{member.id}" %>'" class="left-corner"><%= member.name %></td>
              <td onclick="location.href='<%="/members/#{member.id}" %>'" ><%= member.load %></td>
              <td onclick="location.href='<%="/members/#{member.id}" %>'" ><%= t("boolean.#{member.exit_cycle}") %></td>
              <td class="has-text-centered right-corner">

              <!--  
                <%= link_to "/members/#{member.id}" do%>
                  <i class="far fa-eye"></i> Mostrar
                <%end%>
                <%= link_to "/members/#{member.id}/edit" do%>
                  <i class="fas fa-edit"></i> Editar
                <% end %>
                <%= link_to "/members/#{member.id}", method: :delete, data: { confirm: 'Are you sure?'} do %>
                  <i class="fas fa-trash-alt"></i> Remover
                <% end %>
-->

                <div class="crud-hover">  
                  <div class="card crud-options">
                    <footer class="card-footer">
                      <%= link_to "/members/#{member.id}/edit", class:"crud-edit" do%>
                        <i class="fas fa-edit"></i> 
                        <div class="crud-text"> 
                          Editar
                        </div>
                      <% end %>
                      <%= link_to "/members/#{member.id}" , method: :delete, data: { confirm: 'Are you sure?' }, class:"crud-delete" do%>
                        <i class="fas fa-trash-alt"></i> 
                        <div class="crud-text">  
                          Remover
                        </div>
                      <% end %>
                      <div class="crud-options-triangle">
                      </div>  
                    </footer>
                  </div>
                </div>

                <i class="fas fa-ellipsis-h"></i>

              </td>
              
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>
    <button class="button is-success ">
      <%= link_to new_member_path do %>
        <i class="fas fa-plus"></i> Novo Membro
      <% end %>
    </button>
  </div>
</section>

app/views/members/new.html.erb
<div class="columns is-centered mt-5">
  <div class="column is-one-third">
    <h1 class="subtitle">New Member</h1>

    <%= render 'form', member: @member %>
    <div class="mt-4 ml-2">
      <%= link_to t('actions.back'), members_path %>
    </div>
  </div>
</div>

app/views/members/show.html.erb
<div class="columns is-centered is-mobile mt-5">
  <div class="column is-four-fifths-mobile is-half-tablet is-two-fifths-desktop is-one-third-widescreen">
    <p id="notice"><%= notice %></p>
    <div class="card mt-3">
      <div class="card-content">

        <div class="title">
          <h1 class="title has-text-centered"><%=Member.model_name.human%></h1>
        </div>
        <hr>

        <h2 class="subtitle">
          <strong><%=Member.human_attribute_name('name')%>:</strong> <%= @member.name %> 
        </h2>
        <hr>

        <h2 class="subtitle">
          <strong><%=Member.human_attribute_name('load')%>:</strong> <%= @member.load %> 
        </h2>
        <h2 class="subtitle">
          <strong><%=t(:development_load)%>:</strong>  <%= @development_load  %> 
        </h2>
        <h2 class="subtitle">
          <strong><%=t(:management_load)%>:</strong>  <%= @management_load %> 
        </h2>
        <hr>

        <h2 class="subtitle">
          <strong><%=Member.human_attribute_name('exit_cycle')%>:</strong> <%= human_boolean @member.exit_cycle  %> 
        </h2>
        <hr>

        <strong><%=t(:developed_projects)%>:</strong>

        <p>
          <% @member.developed_projects.each do |project|%>
            <p> <%= project.name %> </p>
          <% end %>
        </p>
        <hr>

        <strong><%=t(:managed_projects)%>:</strong>

        <p>
          <% @member.managed_projects.each do |project|%>
            <p> <%= project.name %> </p>
          <% end %>
        </p>
        <hr>

        <strong><%=Position.model_name.human(count: 2)%>:</strong>
        <p>
          <% @member.positions.each do |position|%>
            <p> <%= position.name %> </p>
          <% end %>
        </p>

      </div>
    </div>
    <div class="mt-4 ml-2">
      <%= link_to t('actions.edit'), edit_member_path(@member) %> |
      <%= link_to t('actions.back'), members_path %>
    </div>
  </div>
</div>